"""init

Revision ID: a92bfb5887b0
Revises:
Create Date: 2026-04-16 06:51:27.211948

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'a92bfb5887b0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
